### PR TITLE
update to_string: fix build

### PR DESCRIPTION
**Pull request by stephenjlewis**
Updates to current version of the libsyntax ast <type>_to_string API

Also formats all files using rustfmt.

### CODE REVIEW

**Comment by Manishearth** [comment]
This isn't something in current libsyntax; it's something in an older libsyntax (if you check the history there's a commit doing the opposite of this). You need to upgrade your nightly. Clippy is broken on today's nightly as well, but I'll fix that soon.

**Comment by Manishearth** [comment]
(Regarding rustfmt: thanks for the patch! However there are some things we'd like to configure about rustfmt before applying it. I'll have a closer look later today when I'm not on mobile)

**Comment by stephenjlewis** [comment]
Yep, realized that as soon as the tests ran -- turns out the nightly binary package I've been using isn't rebuilt as often as you'd expect. Should have closed this PR then.

Not surprised you've reconfigured rustfmt: it occurred to me when it touched so many lines. I've found setting up rustfmt.toml helpful: if you want to dump the flags you use here, I could put the file together.

**Comment by Manishearth** [comment]
Oh, I haven't configured it yet; but I want to. Basically, the stuff where it breaks function declarations and calls to one argument per line is the only thing we don't want. It has modes (at least for declarations, can't remember if it's there for calls), so that it breaks them into just enough lines to not hit the line limit. If you can run it with the flags (if one of them doesn't exist, that's okay), I'll merge it (merge the config file too)!

**Pull request closed without merging**
