### PR TITLE
suggest `a op= b` over `a = a op b`

### PR DESCRIPTION
**Pull request by oli-obk**
since not everyone likes the assign-ops, I also added a restriction lint to forbid assign-ops. Can we somehow make lints depend on each other? like lint if both `assign_ops` and `assign_op_pattern` are active?

### CODE REVIEW

**Comment by llogiq** [comment]
If they want all the warnings, give them all the warnings :smile:

**Comment by llogiq** [comment]
Another thought: Maybe differentiate ops where the assign op is specialized, because those likely improve performance, but may also change behavior.

**Comment by oli-obk** [comment]
> Maybe differentiate ops where the assign op is specialized because those likely improve performance

That's what we want

> but may also change behavior.

*shudder* Maybe I should make an RFC that states that the assign ops should be logically equivalent to the full expression. Is there any reason why they shouldn't?

**Comment by llogiq** [comment]
The original RFC that introduced the OpAssign traits already states exactly that. However, it is really hard to guarantee. Someone has probably already written a quickcheck template, though.

**Comment by oli-obk** [comment]
> However, it is really hard to guarantee.

we don't need to guarantee it, we can depend on it. If anything, this lint will expose such oddities

**Comment by oli-obk** [comment]
I added your concern to the known problems field of the docs

**Comment by llogiq** [comment]
Couldn't we detect if the type impls `Op` and avoid reporting otherwise?

**Comment by oli-obk** [comment]
We can, but the point of the restriction is to forbid all assign ops, no matter if there are no alternatives. What I can do is add a lint to detect assign op impls withou an op impl

**Comment by llogiq** [comment]
Ok then. LGTM.

**Pull request merged**
