### PR TITLE
Rustup to rustc 1.10.0-nightly (645dd013a 2016-04-24); release 0.0.64

### PR DESCRIPTION
**Pull request by Manishearth**
Doesn't yet pass tests

### CODE REVIEW

**Comment by Manishearth** [comment]
I don't have the time to look at these failures (exams going on): @mcarton / @llogiq could you have a look when you get time?

**Comment by llogiq** [comment]
It's getting late here, so perhaps tomorrow morning.

**Comment by Manishearth** [comment]
cool, no hurry. I'll get to it in two days otherwise

**Comment by llogiq** [comment]
There are still some failing tests; alas I don't have time to fix them now.

**Comment by mcarton** [comment]
@Manishearth, @llogiq r?

**Comment by llogiq** [comment]
Thanks @mcarton!

**Pull request merged**
