### PR TITLE
eq_op: cut back to expressions that are guaranteed side effect free

### LINKED ISSUE #229: false positives in eq_op lint
I just got this false positive when running clippy over racer:

```
src/racer/cargo.rs:314:12: 314:30 warning: equal expressions as operands to &&, #[warn(eq_op)] on by default
src/racer/cargo.rs:314         if f.pop() && f.pop() {
                                  ^~~~~~~~~~~~~~~~~~
```

I think the eq_op lint should be reduced a lot. Equal expressions at the AST level are not guaranteed to have the same result, and of course may have side effects too.

The lint should only look for simple expressions like consts (using const eval), variable lookups, field access and maybe casts to primitive types. Even operator application can have side effects.

### PR DESCRIPTION
**Pull request by birkenfeld**
fixes #229

### CODE REVIEW

**Comment by llogiq** [comment]
As I said on #229, I think the right way to solve this is with a blacklist of known pure functions.

**Comment by Manishearth** [comment]
Yeah, but incrementally solving this is better :smile:

**Comment by Manishearth** [comment]
lgtm

**Comment by llogiq** [comment]
Ok then.

**Pull request merged**
