### PR TITLE
misc: if "match -> if let" lint with code in second arm (fixes #172)

### LINKED ISSUE #172: single_match suggestion should handle else blocks
```
match x {
 something => {foo}
 _ => {bar}
}
```

gets the suggestion

```
if let something = x {
 foo
}
```

but it should get the suggestion

```
if let something = x {
 foo
} else {
 bar
}
```

Just needs some extra snippets in https://github.com/Manishearth/rust-clippy/blob/master/src/misc.rs#L50 if there is an else block

### PR DESCRIPTION
**Pull request by birkenfeld**

### CODE REVIEW

**Comment by Manishearth** [comment]
Fails the dogfood tests.

On second thought, should we be suggesting `if let ... else` over `match` at all? They both rank mostly the same in my mind. Thoughts? @llogiq

**Comment by birkenfeld** [comment]
I'd prefer `if let` since it's one less nesting level.

**Comment by birkenfeld** [comment]
That said, the case with a nonempty `else` clause is maybe not so clear.

**Comment by Manishearth** [comment]
Yeah, I'm only talking about the cases where an else clause is needed.

**Comment by birkenfeld** [comment]
Another case is where both the expression to match and the pattern are pretty long, so that it's necessary to break them into two lines anyway.

But counting characters is probably not something a lint should do?

**Comment by Manishearth** [comment]
We could count chars. I'm okay with not linting when certain char lengths are too much.

(The reverse -- making a lint stronger with char length checks -- is not something I want)

**Comment by birkenfeld** [comment]
Hm, of the "fixes" I made for dogfood to pass, I'm not sure I would write them with `if let` in the first place. Please have a look.

**Comment by Manishearth** [comment]
So #rust seems to be divided on this.

We can add a Cargo feature "aggressive_single_match" that turns on else-checking; IMO it's a nice thing to have.

**Comment by llogiq** [comment]
I like `if let .. { Some(..) } else { None } better than a match, but I would not exactly lint it.

I vote skip linting if let with else.

**Comment by Manishearth** [comment]
Merged the other one.

We can add an optional cargo feature later that does this more involved check

**Pull request closed without merging**
