### PR TITLE
Update to compiletest_rs 0.2.6

### PR DESCRIPTION
**Pull request by luisbg**
There is a new version of compiletest_rs, is it worth bumping the dependency version?

### CODE REVIEW

**Comment by luisbg** [comment]
Part of the reason I noticed the version bump is because 0.2.6 fails to build for me.

But I am expecting it to be fixed shortly :smile: 

error[E0433]: failed to resolve. Could not find `Options` in `test`
   --> src/lib.rs:146:18
    |
146 |         options: test::Options::new(),
    |                  ^^^^^^^^^^^^^^^^^^ Could not find `Options` in `test`

error[E0560]: struct `test::TestOpts` has no field named `options`
   --> src/lib.rs:146:9
    |
146 |         options: test::Options::new(),
    |         ^^^^^^^^ `test::TestOpts` does not have this field

error: aborting due to previous error

error: Could not compile `compiletest_rs`.

**Comment by oli-obk** [comment]
You just need to update your nightly ;)

**Comment by luisbg** [comment]
Oh! It didn't occur to me to update Nightly. It should become a habit.

The interesting thing is that after the update 0.2.5 doesn't work and 0.2.6 is needed, which makes this version bump necessary.

**Comment by luisbg** [comment]
Thanks @oli-obk :smile:

**Pull request merged**
