### PR TITLE
Rustup to *rustc 1.11.0-nightly (763f9234b 2016-06-06)*

### LINKED ISSUE #992: Error installing with nightly
Error installing using `rustup run nightly cargo install clippy` on debian jesse and OSX 10.11.3
```
vagrant@debian-jessie:~$ rustup run nightly cargo -V
cargo 0.12.0-nightly (510920b 2016-06-06)
vagrant@debian-jessie:~$ rustup run nightly rustc -V
rustc 1.11.0-nightly (763f9234b 2016-06-06)
```
```
vagrant@debian-jessie:~$ rustup run nightly cargo install clippy
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading clippy v0.0.74
 Downloading rustc-serialize v0.3.19
 Downloading quine-mc_cluskey v0.2.2
 Downloading clippy_lints v0.0.74
 Downloading semver v0.2.3
 Downloading unicode-normalization v0.1.2
 Downloading regex-syntax v0.3.3
 Downloading toml v0.1.30
 Downloading matches v0.1.2
 Downloading nom v1.2.3
   Compiling rustc-serialize v0.3.19
   Compiling unicode-normalization v0.1.2
   Compiling quine-mc_cluskey v0.2.2
   Compiling matches v0.1.2
   Compiling nom v1.2.3
   Compiling semver v0.2.3
   Compiling regex-syntax v0.3.3
   Compiling toml v0.1.30
   Compiling clippy_lints v0.0.74
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.74/src/misc.rs:185:16: 185:19 error: mismatched types [E0308]
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.74/src/misc.rs:185         val == 0.0 || val == ::std::f64::INFINITY || val == ::std::f64::NEG_INFINITY
                                                                                                   ^~~
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.74/src/misc.rs:185:16: 185:19 help: run `rustc --explain E0308` to see a detailed explanation
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.74/src/misc.rs:185:16: 185:19 note: expected type `rustc_const_math::ConstFloat`
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.74/src/misc.rs:185:16: 185:19 note:    found type `_`
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.74/src/misc.rs:185:30: 185:50 error: mismatched types [E0308]
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.74/src/misc.rs:185         val == 0.0 || val == ::std::f64::INFINITY || val == ::std::f64::NEG_INFINITY
                                                                                                                 ^~~~~~~~~~~~~~~~~~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.74/src/misc.rs:185:30: 185:50 help: run `rustc --explain E0308` to see a detailed explanation
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.74/src/misc.rs:185:30: 185:50 note: expected type `rustc_const_math::ConstFloat`
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.74/src/misc.rs:185:30: 185:50 note:    found type `f64`
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.74/src/misc.rs:185:61: 185:85 error: mismatched types [E0308]
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.74/src/misc.rs:185         val == 0.0 || val == ::std::f64::INFINITY || val == ::std::f64::NEG_INFINITY
                                                                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.74/src/misc.rs:185:61: 185:85 help: run `rustc --explain E0308` to see a detailed explanation
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.74/src/misc.rs:185:61: 185:85 note: expected type `rustc_const_math::ConstFloat`
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.74/src/misc.rs:185:61: 185:85 note:    found type `f64`
error: aborting due to 3 previous errors
error: failed to compile `clippy v0.0.74`, intermediate artifacts can be found at `/tmp/cargo-install.VxmKaOYhFHxR`
```

PS. Sorry if I missed some guidelines on issues for the project, I didn't see anything in the guidelines.

### PR DESCRIPTION
**Pull request by mcarton**
Fix #992.

### CODE REVIEW

**Comment by mcarton** [comment]
Hu, for some reason Travis is stuck to *rustc 1.11.0-nightly (1c975eafa 2016-06-05)*.

**Comment by mcarton** [comment]
Ah… the *pr* build was on *rustc 1.11.0-nightly (1c975eafa 2016-06-05)* and the *push* build was on *rustc 1.11.0-nightly (763f9234b 2016-06-06)*. Cache problem?

**Comment by llogiq** [comment]
When I tried to update this morning, my rustup didn't want to update because of some (apparently intermittent) signature error. Perhaps that's the reason one machine still had the 'old' rustc.

**Comment by mcarton** [comment]
Travis redownloads Rust for every build using rustup.

**Pull request merged**
