### PR TITLE
 Rustup to rustc 1.12.0-nightly (1225e122f 2016-07-30)  and bump to 0.0.80

### LINKED ISSUE #1120: Clippy 0.79 does not compile with rustc nightly 2016-07-24
When I try compiling a project with clippy using rustc nightly 2016-07-24, I get the following error:

```
   Compiling clippy_lints v0.0.79
/Users/nm46057/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.79/src/utils/mod.rs:500:14: 500:35 error: no associated item named `from_spans` found for type `syntax::codemap::MultiSpan` in the current scope 
/Users/nm46057/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.79/src/utils/mod.rs:500         msp: MultiSpan::from_spans(sugg.iter().map(|&(span, _)| span).collect()),
                                                                                                                     ^~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error 
error: Could not compile `clippy_lints`.

To learn more, run the command again with --verbose.
```

### PR DESCRIPTION
**Pull request by mcarton**
Yup, there's been another problem after  #1119.
Fix #1120.
Ref https://github.com/rust-lang/rust/pull/35090.

### CODE REVIEW

**Comment by mcarton** [comment]
Argh, Travis is always picking *rustc 1.12.0-nightly (f164cf5d6 2016-07-29)*, I'll try again later.

**Comment by mcarton** [comment]
Well, Travis still won't cooperate and I'm off for the week.
@Manishearth, @oli-obk , @llogiq, @birkenfeld: Can one of you publish the crates? :smile:

(>10h cache for a nightly seems excessively long :confused:)

**Comment by Manishearth** [comment]
Will do :smile:

**Comment by oli-obk** [comment]
> error: api errors: crate name has already been claimed by another user

huh.. cargo publish doesn't like me, I'll go read some cargo docs

**Comment by oli-obk** [comment]
oh oh... only @mcarton owns the clippy_lints package... This means that ever since the split only @mcarton has published the crates xD *tips hat*

**Comment by Manishearth** [comment]
@mcarton could you `cargo owner -a Manishearth` and `cargo owner -a oli-obk` in the clippy_lints folder? (I'll add the rest)

I've pinged Alex to see if he can manually add me as an owner so that we don't have to wait for your vacation to get over 😄

**Comment by Manishearth** [comment]
Alex helpfully gave me access. Published, and added owners.

**Comment by mcarton** [comment]
> oh oh... only @mcarton owns the clippy_lints package...

Oops, did not realize that :smile:

Thanks to Alex!

**Pull request merged**
