### PR TITLE
added the rest of the link help messages

### LINKED ISSUE #210: Links to the wiki
Now that the wiki has been started, we should link to it:

- [x] README.md – I'd have added it, but wouldn't want to mess up the table layout :smile:
- [ ] help- or note-messages in the respective lints?

@Manishearth Also should we add an L-documentation Label to our issues?

### PR DESCRIPTION
**Pull request by llogiq**
This closes #210

### CODE REVIEW

**Comment by Manishearth** [comment]
Why not just make this a macro which constructs this string, using http://manishearth.github.io/rust-internals-docs/rustc/lint/struct.Lint.html#method.name_lower?

**Comment by llogiq** [comment]
Sounds good. I've not yet written too much macro code, this looks like a good way to learn this. :smile:

**Comment by Manishearth** [comment]
Actually it can be a function :)

**Comment by llogiq** [comment]
Actually, we could even use our `span_lint` function for it. It already has all needed information.

**Comment by Manishearth** [comment]
perfect!

**Comment by llogiq** [comment]
This is now removing the individual `span_help_and_lint` calls that just add the link, changing the implementations in `util.rs` instead. It should now work nicely with all lints we're going to add in the future. This however means we should add a section in the wiki whenever we add a new lint, or the link will go to the wiki header instead.

**Comment by Manishearth** [comment]
Something went horribly wrong in your git-ting :(

**Comment by llogiq** [comment]
Yep, I just noticed, too :sweat: 

Does this look better?

**Comment by Manishearth** [comment]
Not as good as it could be, but good enough

**Pull request merged**
