### PR TITLE
new lint: unicode_not_nfc

### LINKED ISSUE #85: Various unicode warnings [zero-width-space, unicode_canon, ascii_only]
[This program](http://is.gd/ChFuOE) should warn that zero-width spaces are being used directly and should be replaced with their unicode escape code (`\u{200B}`).

See [Unicode spaces](https://www.cs.tut.fi/~jkorpela/chars/spaces.html) for more information on them.

### PR DESCRIPTION
**Pull request by llogiq**
This closes #85 – I just renamed the lint to make it more clear. Wiki entry will follow once pulled.

I also want to note that once this gets pulled, we will have reached the **50 lints** mark! Yay! :smile:

@Manishearth r?

### CODE REVIEW

**Comment by llogiq** [comment]
Let this be a testament to my ineptitude for working with anything more complex than SVN. :smile:

**Comment by llogiq** [comment]
Since Manish seems to be awfully busy, @birkenfeld r?

**Comment by Manishearth** [comment]
(I wasn't awfully busy, my github emails were being sent to spam for some reason. But now I *am* busy :stuck_out_tongue: )

**Comment by llogiq** [comment]
I was referring to [your work week](https://www.reddit.com/r/rust/comments/3j2820/whats_everyone_working_on_this_week_week_36_2015/culmyx7) :stuck_out_tongue_winking_eye:

**Comment by birkenfeld** [comment]
Well, it seems to work as advertised, however I wonder if it's a good idea to emit a warning for *each* such sequence.

(Similar for the "non-ASCII char" lint, I think that should be restricted to at most once per string literal).

If you just do a pass that checks for the first mismatch between `string` and `string.nfc().collect()` that might be less intrusive, and need less convoluted control flow. If you want to keep the current code, I would request better names for "last" and "ustart" :)

**Comment by Manishearth** [comment]
Once per stringlit sounds good to me (emit the list of chars if you want)

**Comment by llogiq** [comment]
I'd really like to show where in the string literal the problematic characters are. Can we report multiple spans in one line?

@birkenfeld Thanks, I'll think about the variable names. I'd really like to keep the convoluted control flow, because I believe showing the locations where things go wrong (which btw. is a bit broken because zero-width whitespace throw off the formatting) is a really useful feature.

**Comment by Manishearth** [comment]
No, but multispan reporting is a desired feature for rustc (e.g. for unused imports)

**Comment by birkenfeld** [comment]
BTW, does "showing the locations" do useful things in the case of multiline string literals?

**Comment by llogiq** [comment]
It should. Until now I had no problems with reporting on multiline snippets.

Since we don't have the means to make the report uncluttered, I'll report the whole string, along with pairs of sequences to search/replace.

**Comment by Manishearth** [comment]
Make sure to add special handling for the language when you have a single bad char!

**Comment by llogiq** [comment]
Will do. Alas, it'll have to wait – I'm a bit busy ATM.

**Comment by llogiq** [comment]
Now I've special-cased the one-range case so that the respective part of the string is spanned. In the other cases, a newline-joined list of ranges + suggested replacements is reported with the whole string as span.

@Manishearth @birkenfeld r?

**Comment by llogiq** [comment]
Since the solution to the problem does not involve seeing the actual ranges, I created a far less complex version that directly lints the strings and suggests replacements. I'm closing this in favor of the other solution.

**Pull request closed without merging**
