### PR TITLE
[WIP] Lint equal match arms

### LINKED ISSUE #616: Lint: Equal match arms
If we have two equal non-empty match arms, they can be unified. E.g.

```
match foo {
    bla => bar(),
    blubb => bar(),
    _ => blob(),
}

// should be written as
match foo {
    bla | blubb => bar(),
    _ => blob(),
}
```

This is the same as #80, but with more statements to choose from – the difficulty will be to somehow order the match arms so that only potentially equal arms get compared, because comparing each arm would be in O(n²) for n match arms, which could get unwieldy.

### PR DESCRIPTION
**Pull request by mcarton**
Fix  #616.

There is a problem in the `PartialEq` implementation for `consts::Constant`: it is not transitive (eg. `42.0 == 42.0f32` and `42.0 == 42.0f64` but `42.0f32 != 42.0f64`.
This means I cannot implement a proper hash function. Should I remove the [width check](https://github.com/Manishearth/rust-clippy/blob/af07ccc16cbf9a736a5aba2759f296242636fecc/src/consts.rs#L107-L110) and make it consider `42.0f32 == 42.0f64`?

### CODE REVIEW

**Comment by Manishearth** [comment]
We're only using the hash to check equality once, right? In that case, are they necessary?

**Comment by mcarton** [comment]
We’re checking in a list of expressions or blocks if any two are equal. It would be *O(n²)* without hashes.
A non-transitive `PartialEq` is bad anyway.

**Comment by llogiq** [comment]
I don't have a problem with mostly ignoring the type for integers (as long as we keep the sign), but note that other types may also be problematic (e.g. `f`*xx*`::NAN`).

**Comment by mcarton** [comment]
> note that other types may also be problematic (e.g. fxx::NAN).

`NaN` values make the order non-total but it still is transitive.

**Comment by llogiq** [comment]
Yeah, but NaN != NaN, whereas ConstFloat(NaN, _) should equal itself. One thing to be careful of.

**Comment by mcarton** [comment]
@llogiq well, it currently [does not, `ConstFloat`s are compared with `f64::eq`](https://github.com/Manishearth/rust-clippy/blob/master/src/consts.rs#L103-L116).

**Comment by llogiq** [comment]
Ok, I think I should change that. But don't worry about it, I can handle that in another PR.

**Comment by mcarton** [comment]
Done, but it looks like #652 will have to be merged first.

**Comment by mcarton** [comment]
Merged, travis is happy now.

**Pull request merged**
