### PR TITLE
Suggest `.get()` over `.iter().nth()`

### PR DESCRIPTION
**Pull request by devonhollowood**
Implement #1009. Additionally, implement the same check for `Vec`s.

### CODE REVIEW

**Comment by llogiq** [comment]
The travis build error comes from `regex_macros`, it appears.

**Comment by Manishearth** [comment]
passes locally for me, without regex. thanks!

**Comment by mcarton** [comment]
This could also lint on `VecDeque` and `iter_mut().nth()` vs. `get_mut()`.

**Comment by llogiq** [comment]
@mcarton good idea.

**Comment by llogiq** [comment]
@devonhollowood good work. Thank you!

**Pull request merged**
