### PR TITLE
Rewrite `doc_markdown` to use `pulldown-cmark`

### LINKED ISSUE #1469: False doc_markdown warnings
When I use `cfg_attr` for conditional examples in doc comments like this:

```rust
#![cfg_attr(feature = "a", doc = " ```")]
#![cfg_attr(not(feature = "a"), doc = " ```ignore")]
//! fn main() {
//!     let s = "localhost:10000".to_string();
//!     println!("{}", s);
//! }
//! ```
```

I receive false warnings:

```
cargo clippy --features a
...
warning: you should put `to_string` between ticks in the documentation, #[warn(doc_markdown)] on by default
  --> src/lib.rs:66:35
   |
66 | //!     let s = "localhost:10000".to_string();
   |                                   ^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by mcarton**
Rewrite `doc_markdown` to use `pulldown-cmark`.

This should fix a number of false positives and true negatives. It should mean that the lint can be extended more easily in the futur.

~WIP: I have not got the spans quite right yet. The best I can do is line-wise (actually attribute-wise) spans, while the current lint report the actual problematic word.~

Fix #1469.

### CODE REVIEW

**Comment by killercup** [comment]
Yes! [This is gonna be good](https://github.com/killercup/rust-docstrings)

**Comment by mcarton** [comment]
This is ready to be merged.

**Comment by mcarton** [comment]
Appveyor build looks to have failed because of caching problem.

**Comment by mcarton** [comment]
The windows build is failing because of

```
------stderr------------------------------
error[E0464]: multiple matching crates for `pulldown_cmark`
  --> clippy_lints/src/lib.rs:55:1
   |
55 | extern crate pulldown_cmark;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: candidates:
   = note: path: \\?\C:\projects\rust-clippy\clippy_tests\target\debug\deps\libpulldown_cmark-2b392b6bad2227f1.rlib
   = note: crate name: pulldown_cmark
   = note: path: \\?\C:\Users\appveyor\.rustup\toolchains\nightly-i686-pc-windows-gnu\lib\rustlib\i686-pc-windows-gnu\lib\libpulldown_cmark-650d3ff121d3d129.rlib
   = note: crate name: pulldown_cmark
error[E0463]: can't find crate for `pulldown_cmark`
  --> clippy_lints/src/lib.rs:55:1
   |
55 | extern crate pulldown_cmark;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
error: aborting due to previous error(s)
```

Any idea what is going on?

**Comment by oli-obk** [comment]
Rustc is distributing its own pulldown... somehow we're getting a conflict with the distributed one. Do we set any unusual path env var values in appveyor?

**Comment by mcarton** [comment]
[Looks like we do.](https://github.com/Manishearth/rust-clippy/blob/892cc2833c63a4c3ed2df82c99d200f6fb9f11c2/appveyor.yml#L18) Cc @llogiq, I've no idea how either Appveyor or Windows work.

**Comment by mcarton** [comment]
This works \o/
Any objection to merging?

**Comment by Manishearth** [comment]
No, but I would like a quick performance comparison.

**Comment by oli-obk** [comment]
You can remove my two commits then. Seems they had no effect and were messy to begin with

**Comment by mcarton** [comment]
Before:
`diesel`: (3767 lines staring with `//[/!]`)
```
time: 0.036; rss: 114MB	early lint checks
time: 0.036; rss: 113MB	early lint checks
time: 0.036; rss: 113MB	early lint checks
```

`serde`: (3111 lines staring with `//[/!]`)
```
time: 0.034; rss: 111MB	early lint checks
time: 0.034; rss: 111MB	early lint checks
time: 0.034; rss: 111MB	early lint checks
```

`clippy_lints`: (10809 lines staring with `//[/!]`)
```
time: 0.034; rss: 178MB	early lint checks
time: 0.029; rss: 178MB	early lint checks
time: 0.030; rss: 182MB	early lint checks
```

After:
`diesel`:
```
time: 0.038; rss: 113MB	early lint checks
time: 0.039; rss: 114MB	early lint checks
time: 0.036; rss: 114MB	early lint checks
```

`serde`:
```
time: 0.034; rss: 111MB	early lint checks
time: 0.033; rss: 113MB	early lint checks
time: 0.037; rss: 113MB	early lint checks
```

`clippy_lints`:
```
time: 0.033; rss: 179MB	early lint checks
time: 0.030; rss: 183MB	early lint checks
time: 0.030; rss: 181MB	early lint checks
```

Does not look like there is much of a difference. Any idea of a biggish crate with a lot of docs?
[(It also indirectly found dead links in diesel)](https://github.com/diesel-rs/diesel/pull/943) :smile:

**Comment by Manishearth** [comment]
(feel free to merge, fwiw)

**Pull request merged**
