### PR TITLE
New lint for statement with no effect

### PR DESCRIPTION
**Pull request by sanxiyn**
This is an implementation of rust-lang/rust#16170.

Many extensions are possible (tuples, for example), but this implements just struct/enum constructors.

### CODE REVIEW

**Comment by Ryman** [comment]
Theoretically, if any of these unit structs implemented `Drop` it could have an effect?

**Comment by sanxiyn** [comment]
Yes, Drop should be considered. On the other hand, `HasDrop;` is still worth warning, because the destructor will run immediately, which is usually not the intention. You need to use `let` to run the destructor at the end of the block.

**Comment by llogiq** [comment]
I too think that at least the lint message should be different when the constructed type implements Drop. Perhaps even give it another lint specifier – what about `naked_drop`?

**Comment by Manishearth** [comment]
Personal preference is that we should not have an extra lint -- I'm okay with both warning and not warning on Drop.

**Comment by Manishearth** [comment]
As far as the rest of it goes, we should add a macro check (`in_macro`), otherwise LGTM

**Comment by sanxiyn** [comment]
Added the macro check. Leaving warning on Drop as-is, we can open a follwup issue for that. See also discussion on Rust's built-in lint re Drop at rust-lang/rust#21775.

**Comment by llogiq** [comment]
LGTM.

**Pull request merged**
