### PR TITLE
Remove and lint about useless braces in `else { if .. }`

### PR DESCRIPTION
**Pull request by mcarton**
Clippy had surprisingly lots of those.
The `SUGGESTION` in the tests seem to be ignored, I don't know what I've done wrong :confused:.

### CODE REVIEW

**Comment by Manishearth** [comment]
Tests will not fail if you have failed to mention a HELP/NOTE/SUGGESTION (however if you do mention them they will fail if it doesn't match with the actual output)

**Comment by mcarton** [comment]
If I replace the suggestion by anything [here](https://github.com/mcarton/rust-clippy/commit/c2444c604388f96a6949bb39bcf3730c6ef78c0f#diff-40772c2b367059f21a235684ce3b1edfR23), the tests still pass.
Eg. I've pushed a ` should-break` branch, [this commit](https://github.com/mcarton/rust-clippy/commit/d7308a287ad32b53c87abcf98d8bfc292a022b7f) should break the tests, but it [does not](https://travis-ci.org/mcarton/rust-clippy/builds/102165260).

**Comment by Manishearth** [comment]
@sanxiyn is something broken in compiletest?

**Comment by oli-obk** [comment]
This might be the issue I have noticed with colons after `ERROR`, @mcarton, try removing the colon where you tried to break the tests but didn't

**Comment by mcarton** [comment]
@oli-obk [without the colon](https://github.com/Manishearth/rust-clippy/commit/25f4ab08ff8ab39e379c99551dfce4fd5641bb62) it still does [not check for the suggestion](https://travis-ci.org/mcarton/rust-clippy/builds/103316185#L175).

**Comment by Manishearth** [comment]
Seems to pass now. 

The fallout on this one is amazing.

Thanks!

**Pull request merged**
