### PR TITLE
fixed callback changes from rustc 1.14.0-nightly (7c69b0d5a 2016-11-01)

### LINKED ISSUE #1320: 0.0.96 does not compile on the latest nightly
See https://travis-ci.org/Manishearth/rust-clippy/builds/169746235.

Looks like *clippy v0.0.96* does not compile on *rustc 1.14.0-nightly (7c69b0d5a 2016-11-01)*.
I just moved in and don't have a real Internet access (or a bed) yet, so I won't be able to fix this one.

### PR DESCRIPTION
**Pull request by EpicatSupercell**
Should fix #1320

### CODE REVIEW

**Comment by oli-obk** [comment]
thanks!

**Comment by mcarton** [comment]
@oli-obk could you push a `v0.0.97` tag too? :heart:

**Comment by oli-obk** [comment]
Pushed a tag, I hope I did that right... we need to write down our steps required for release...

**Comment by mcarton** [comment]
Here is what I usually do¹:

1. `cargo test`.
- Bump `package.version` in `./Cargo.toml` (no need to manually bump `dependencies.clippy_lints.version`).
- Run `./util/update_lints.py`.
- Write a changelog entry.
- Commit `./Cargo.toml`, `./clippy_lints/Cargo.toml` and `./CHANGELOG.md`.
- `git push`
- Wait for Travis's approval.
- Merge.
- `cargo publish` in `./clippy_clints`.
- `cargo publish` in the root directory.
- `git pull`.
- `git tag -s v0.0.X`.
- `git push --tags`.

Should I put that somewhere? (If so, where?)

---

(1: obviously I forgot something, I'm writing that from memory)

**Comment by oli-obk** [comment]
> Should I put that somewhere? (If so, where?)

I copied the steps to https://github.com/Manishearth/rust-clippy/blob/master/PUBLISH.md

**Pull request merged**
