### PR TITLE
Update rust to 0efb9dab8c7c07fa28e9df0eccc5c07ea3c17fbb

### PR DESCRIPTION
**Pull request by Manishearth**
Contains HIR, plus my fixes for lints. Needs next nightly (half a day)to land.

### CODE REVIEW

**Comment by birkenfeld** [comment]
So the HIR seems to be *very* similar to the AST, if all you needed to do was change use paths. Can you give a short description of what are (or will be) the main differences?

**Comment by birkenfeld** [comment]
Also, why is there `rustc_front` and `rustc::front`? Sounds like a recipe for confusion.

**Comment by Manishearth** [comment]
The AST contains pre-expansion data and other things. The HIR is more of an abstract IR which both the AST and future MIR can be lowered to. At the moment it's pretty much a copy; this will change in the future.

`rustc` does that multicrate thing in other places already; `librustc_*` are all logically one crate, just split up for compilation speed reasons.

**Comment by birkenfeld** [comment]
MIR is lowered to HIR? Wouldn't it be AST->HIR->MIR->LLIR?

**Comment by Manishearth** [comment]
No, MIR is different. I'm not sure how it works exactly.

**Pull request merged**
