### PR TITLE
Rudimentary escape analysis for Box<T>

### PR DESCRIPTION
**Pull request by Manishearth**
Not sure if this should be merged yet, but it seems to work so far.

We probably won't see any results from this until I add Vec<T> and String to this; I haven't seen much Box-abuse.

### CODE REVIEW

**Comment by Manishearth** [comment]
The purpose of this is to avoid allocations whenever possible, using the corresponding value types instead. I.e. `T` instead of `Box<T>`, `[T; N]` instead of `Vec<T>`, `&'static str` instead of `String`. This is achieved by tracking all boxed local variables, and ensuring they get moved out or borrowed without autoderef/coercion at least once. (`vec.push()` is an example of such a borrow; `vec.len()` or `vec.iter()` is not)

**Comment by llogiq** [comment]
I'm unsure about the Vec<T> case, because not all arrays fit on the stack – perhaps have a size limit?

**Comment by Manishearth** [comment]
huh, right. We can always cap it, though.

**Comment by llogiq** [comment]
LGTM otherwise :+1: I think this is immediately useful. Let's merge and add the other parts later.

**Pull request merged**
