### PR TITLE
Unicode lints, second attempt: Lint whole strings, help with replacement

### LINKED ISSUE #85: Various unicode warnings [zero-width-space, unicode_canon, ascii_only]
[This program](http://is.gd/ChFuOE) should warn that zero-width spaces are being used directly and should be replaced with their unicode escape code (`\u{200B}`).

See [Unicode spaces](https://www.cs.tut.fi/~jkorpela/chars/spaces.html) for more information on them.

### PR DESCRIPTION
**Pull request by llogiq**
This fixes #85 in a less complex way.

@Manishearth r?

### CODE REVIEW

**Comment by Manishearth** [comment]
LGTM, needs new nightly

**Comment by Manishearth** [comment]
Fails dogfood: https://travis-ci.org/Manishearth/rust-clippy/builds/78734055

```
$ bash util/dogfood.sh
   Compiling clippy v0.0.12 (file:///home/travis/build/Manishearth/rust-clippy)
src/unicode.rs:53:32: 53:42 error: zero-width space detected [-D zero-width-space]
src/unicode.rs:53                 string.replace("\u{200B}", "\\u{200B}")));
                                                 ^~~~~~~~~~
src/unicode.rs:53:32: 53:42 help: Consider replacing the string with:
"\u{200B}"
for further information visit https://github.com/Manishearth/rust-clippy/wiki#zero_width_space
src/unicode.rs:53:32: 53:42 error: literal non-ASCII character detected [-D non-ascii-literal]
src/unicode.rs:53                 string.replace("\u{200B}", "\\u{200B}")));
                                                 ^~~~~~~~~~
src/unicode.rs:53:32: 53:42 help: Consider replacing the string with:
"\u{200b}"
for further information visit https://github.com/Manishearth/rust-clippy/wiki#non_ascii_literal
src/unicode.rs:65:5: 72:6 error: this if statement can be collapsed [-D collapsible-if]
src/unicode.rs:65     if string.chars().zip(string.nfc()).any(|(a, b)| a != b) {
src/unicode.rs:66         if cx.current_level(NON_ASCII_LITERAL) == Level::Allow {
src/unicode.rs:67             span_help_and_lint(cx, UNICODE_NOT_NFC, span,
src/unicode.rs:68                 "non-nfc unicode sequence detected",
src/unicode.rs:69                 &format!("Consider replacing the string with:\n\"{}\"",
src/unicode.rs:70                     string.nfc().collect::<String>()));
                  ...
src/unicode.rs:65:5: 72:6 help: try
if (string.chars().zip(string.nfc()).any(|(a, b)| a != b)) && cx.current_level(NON_ASCII_LITERAL) == Level::Allow {
    span_help_and_lint(cx, UNICODE_NOT_NFC, span,
        "non-nfc unicode sequence detected",
        &format!("Consider replacing the string with:\n\"{}\"",
            string.nfc().collect::<String>()));
}
for further information visit https://github.com/Manishearth/rust-clippy/wiki#collapsible_if
error: aborting due to 3 previous errors
Could not compile `clippy`.
```

Why is it detecting the ZWS when we've escaped it? This seems to be handled by the parser, perhaps we should iterate through the code itself. (And add tests to ensure that this is never caught)

**Comment by Manishearth** [comment]
I rebased it and added a test. Do `git checkout master; git fetch origin; git checkout origin/unicode_str; git checkout -B unicode_str` to fix your local branch (instead of merging).

**Comment by llogiq** [comment]
Thanks. This didn't happen on my (pre-HIR) system; I'm currently updating. So I'll check the snippet for the String literal (instead of the contained InternedString) and hope for the best.

**Pull request merged**
