### PR TITLE
Fix Travis not pushing gh-pages for tags

### PR DESCRIPTION
**Pull request by mcarton**
Turns out `$TRAVIS_BRANCH` is the tag name for tags.

### CODE REVIEW

**Comment by llogiq** [comment]
LGTM.

**Comment by mcarton** [comment]
Does someone has any idea why the symlink works for https://manishearth.github.io/rust-clippy/current/index.html but not for https://manishearth.github.io/rust-clippy/current/, whereas [there](https://github.com/Sidnicious/gh-pages-symlink-test) it works on both?

**Comment by oli-obk** [comment]
@mcarton works for me. Was some cache outdated?

**Comment by mcarton** [comment]
:tada:

**Pull request merged**
