### PR TITLE
Rustup to *1.10.0-nightly (cd6a40017 2016-05-16)*, bump to 0.0.68

### LINKED ISSUE #941: Failed to compile on latest nightly
```
➜  ~ cargo install clippy
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling unicode-normalization v0.1.2
   Compiling quine-mc_cluskey v0.2.2
   Compiling regex-syntax v0.3.1
   Compiling nom v1.2.3
   Compiling rustc-serialize v0.3.19
   Compiling semver v0.2.3
   Compiling toml v0.1.30
   Compiling clippy v0.0.67
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:949:1: 954:2 error: a type named `SelfKind` has already been imported in this module [E0255]
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:949 enum SelfKind {
                                                                                 ^
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:949 use rustc::hir::*;
                                                                                     ^~~~~~~~~~~~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:949:1: 954:2 help: run `rustc --explain E0255` to see a detailed explanation
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/lifetimes.rs:128:13: 128:23 error: unresolved enum variant, struct or const `SelfRegion` [E0419]
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/lifetimes.rs:128             SelfRegion(ref opt_lt, _, _) => input_visitor.record(opt_lt),
                                                                                               ^~~~~~~~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/lifetimes.rs:128:13: 128:23 help: run `rustc --explain E0419` to see a detailed explanation
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/lifetimes.rs:129:13: 129:25 error: unresolved enum variant, struct or const `SelfExplicit` [E0419]
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/lifetimes.rs:129             SelfExplicit(ref ty, _) => walk_ty(&mut input_visitor, ty),
                                                                                               ^~~~~~~~~~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/lifetimes.rs:129:13: 129:25 help: run `rustc --explain E0419` to see a detailed explanation
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/lifetimes.rs:355:13: 355:23 error: unresolved enum variant, struct or const `SelfRegion` [E0419]
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/lifetimes.rs:355             SelfRegion(Some(ref lt), _, _) => checker.visit_lifetime(lt),
                                                                                               ^~~~~~~~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/lifetimes.rs:355:13: 355:23 help: run `rustc --explain E0419` to see a detailed explanation
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/lifetimes.rs:356:13: 356:25 error: unresolved enum variant, struct or const `SelfExplicit` [E0419]
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/lifetimes.rs:356             SelfExplicit(ref t, _) => walk_ty(&mut checker, t),
                                                                                               ^~~~~~~~~~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/lifetimes.rs:356:13: 356:25 help: run `rustc --explain E0419` to see a detailed explanation
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:957:29: 957:42 error: type name `ExplicitSelf_` is undefined or not in scope [E0412]
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:957     fn matches(&self, slf: &ExplicitSelf_, allow_value_for_ref: bool) -> bool {
                                                                                                             ^~~~~~~~~~~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:957:29: 957:42 help: run `rustc --explain E0412` to see a detailed explanation
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:957:29: 957:42 help: no candidates by the name of `ExplicitSelf_` found in your project; maybe you misspelled the name or forgot to import an external crate?
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:959:33: 959:42 error: unresolved enum variant, struct or const `SelfValue` [E0419]
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:959             (&SelfKind::Value, &SelfValue(_)) |
                                                                                                                 ^~~~~~~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:959:33: 959:42 help: run `rustc --explain E0419` to see a detailed explanation
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:960:31: 960:41 error: unresolved enum variant, struct or const `SelfRegion` [E0419]
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:960             (&SelfKind::Ref, &SelfRegion(_, Mutability::MutImmutable, _)) |
                                                                                                               ^~~~~~~~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:960:31: 960:41 help: run `rustc --explain E0419` to see a detailed explanation
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:961:34: 961:44 error: unresolved enum variant, struct or const `SelfRegion` [E0419]
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:961             (&SelfKind::RefMut, &SelfRegion(_, Mutability::MutMutable, _)) |
                                                                                                                  ^~~~~~~~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:961:34: 961:44 help: run `rustc --explain E0419` to see a detailed explanation
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:962:30: 962:40 error: variable `SelfStatic` from pattern #4 is not bound in pattern #1 [E0408]
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:962             (&SelfKind::No, &SelfStatic) => true,
                                                                                                              ^~~~~~~~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:962:30: 962:40 help: run `rustc --explain E0408` to see a detailed explanation
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:963:31: 963:40 error: unresolved enum variant, struct or const `SelfValue` [E0419]
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:963             (&SelfKind::Ref, &SelfValue(_)) |
                                                                                                               ^~~~~~~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:963:31: 963:40 help: run `rustc --explain E0419` to see a detailed explanation
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:964:34: 964:43 error: unresolved enum variant, struct or const `SelfValue` [E0419]
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:964             (&SelfKind::RefMut, &SelfValue(_)) => allow_value_for_ref,
                                                                                                                  ^~~~~~~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:964:34: 964:43 help: run `rustc --explain E0419` to see a detailed explanation
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:965:18: 965:30 error: unresolved enum variant, struct or const `SelfExplicit` [E0419]
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:965             (_, &SelfExplicit(ref ty, _)) => self.matches_explicit_type(ty, allow_value_for_ref),
                                                                                                  ^~~~~~~~~~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:965:18: 965:30 help: run `rustc --explain E0419` to see a detailed explanation
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/len_zero.rs:129:25: 129:42 error: attempted access of field `explicit_self` on type `&rustc::hir::MethodSig`, but no field with that name was found
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/len_zero.rs:129     if let SelfStatic = sig.explicit_self.node {
                                                                                                          ^~~~~~~~~~~~~~~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/lifetimes.rs:55:49: 55:66 error: attempted access of field `explicit_self` on type `&rustc::hir::MethodSig`, but no field with that name was found
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/lifetimes.rs:55             check_fn_inner(cx, &sig.decl, Some(&sig.explicit_self), &sig.generics, item.span);
                                                                                                                                  ^~~~~~~~~~~~~~~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/lifetimes.rs:61:49: 61:66 error: attempted access of field `explicit_self` on type `&rustc::hir::MethodSig`, but no field with that name was found
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/lifetimes.rs:61             check_fn_inner(cx, &sig.decl, Some(&sig.explicit_self), &sig.generics, item.span);
                                                                                                                                  ^~~~~~~~~~~~~~~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:412:52: 412:69 error: attempted access of field `explicit_self` on type `&rustc::hir::MethodSig`, but no field with that name was found
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:412                                 self_kind.matches(&sig.explicit_self.node, false)
                                                                                                                                    ^~~~~~~~~~~~~~~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:412:52: 412:69 note: in this expansion of if_let_chain! (defined in .cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/utils/mod.rs)
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:412:52: 412:69 note: in this expansion of if_let_chain! (defined in .cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/utils/mod.rs)
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:412:52: 412:69 note: in this expansion of if_let_chain! (defined in .cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/utils/mod.rs)
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:426:66: 426:83 error: attempted access of field `explicit_self` on type `&rustc::hir::MethodSig`, but no field with that name was found
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:426                            !self_kinds.iter().any(|k| k.matches(&sig.explicit_self.node, is_copy)) {
                                                                                                                                                  ^~~~~~~~~~~~~~~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:434:39: 434:56 error: attempted access of field `explicit_self` on type `&rustc::hir::MethodSig`, but no field with that name was found
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:434                                       sig.explicit_self.span,
                                                                                                                       ^~~~~~~~~~~~~~~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:450:35: 450:52 error: attempted access of field `explicit_self` on type `&rustc::hir::MethodSig`, but no field with that name was found
.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/methods.rs:450                                   sig.explicit_self.span,
                                                                                                                   ^~~~~~~~~~~~~~~~~
error: aborting due to 7 previous errors
error: failed to compile `clippy v0.0.67`, intermediate artifacts can be found at `/tmp/cargo-install.GvbPJWROufhu`

Caused by:
  Could not compile `clippy`.

To learn more, run the command again with --verbose.
➜  ~ cargo --version
cargo 0.11.0-nightly (4e009a6 2016-05-16)
➜  ~ rustc --version
rustc 1.10.0-nightly (cd6a40017 2016-05-16)
➜  ~ rustup show
installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.10.0-nightly (cd6a40017 2016-05-16)

```

### PR DESCRIPTION
**Pull request by mcarton**
Ref https://github.com/rust-lang/rust/pull/33505.
Fix #941.
Fix tests for #940.

### CODE REVIEW

**Comment by crumblingstatue** [comment]
What is going on here exactly?

This was merged, but it's not present in master.

Did somebody forcibly erase these commits from git history?

**Comment by Manishearth** [comment]
I see them here: https://github.com/Manishearth/rust-clippy/commits/master

**Comment by crumblingstatue** [comment]
> I see them here: https://github.com/Manishearth/rust-clippy/commits/master

Really? That's weird, because I really don't



Not just on GitHub, but I also couldn't pull these changes with git locally.

**Comment by zetok** [comment]
>Did somebody forcibly erase these commits from git history?

Maybe github has a problem? Or @Manishearth sees a local, cached version:

**Comment by Manishearth** [comment]
It's right below "fix typos" for me

**Comment by Manishearth** [comment]
The dates are broken, seems to be a github side issue

**Comment by Manishearth** [comment]
Wait, no, sorry, I don't see them either

**Comment by Manishearth** [comment]
I re-merged the commits

**Comment by Manishearth** [comment]
Also branch-protected master

**Comment by zetok** [comment]
>Also branch-protected master

Err, it doesn't seem to be protected?
no protection

**Comment by Manishearth** [comment]
Fixed, you need to enter your password again to confirm

**Pull request merged**
