### PR TITLE
WIP: fix nightly breakage

### PR DESCRIPTION
**Pull request by oli-obk**
breakage from https://github.com/rust-lang/rust/pull/31487

waiting on regex_macros: https://github.com/rust-lang-nursery/regex/pull/162

### CODE REVIEW

**Comment by oli-obk** [comment]
Clippy's constants have been severly damaged by this, and I don't understand the code, so I rewrote it somewhat and hope it's correct. Can't run the tests locally right now, since stage1 isn't really plugin-capable

**Comment by llogiq** [comment]
LGTM.

**Comment by Manishearth** [comment]
The new nightly has appeared, but regex hasn't been updated

**Comment by mcarton** [comment]
They’ve bumped the version now.

**Comment by llogiq** [comment]
And it works. Merging.

**Comment by mcarton** [comment]
Can we get a version bump?
@oli-obk nice (and huge) work BTW.

**Comment by Manishearth** [comment]
Yeah, I'm on it. I had some trouble building locally due to junk in my target dir.

**Comment by Manishearth** [comment]
and done.

**Comment by mcarton** [comment]
Thanks!

**Pull request merged**
