### PR TITLE
small refactoring, more tests for consts

### PR DESCRIPTION
**Pull request by llogiq**

### CODE REVIEW

**Comment by llogiq** [comment]
It appears my git-fu is still to weak for this. :frowning:

**Comment by birkenfeld** [comment]
You could do a `rebase -i master` and then squash everything into one patch.

**Comment by llogiq** [comment]
Like this? It appears to have worked.

**Comment by birkenfeld** [comment]
Not really :) now you have two merge commits and it's still not based on master.

**Comment by llogiq** [comment]
I'm going to close this and start anew from master. Some day I'm gonna learn how to git. :smile:

**Comment by birkenfeld** [comment]
I don't know what tools you use, but a graphical viewer like `gitk` did (and still does) help me enormously to visualize the DAG.

**Pull request closed without merging**
