### PR TITLE
Fix #518

### LINKED ISSUE #518: New lint for: `panic!("{:?}");`
Surprisingly `rustc` does not error or even warn on:
```
% cat a.rs
fn main() {
    panic!("{:?}");
}
% rustc a.rs 
% echo $!
0
```

This is because when `panic!` has only one argument, it does not go through `format_args!`.
I guess one could write a lint that checks for the first argument to a call to `std::rt::begin_unwind`. I could do that if you think it's worth it. Or maybe you think that should be reported on the std repo and fixed there?

Oh, by the way, [clippy itself is affected by that](https://github.com/Manishearth/rust-clippy/blob/a65a7770b3e16fbe5e350c670d852c2696ce2907/src/consts.rs#L78) :sweat_smile:.

### PR DESCRIPTION
**Pull request by mcarton**
I'm not sure whether the error comes from something I did or whether *compiletest_rs* does not like errors in macros.

### CODE REVIEW

**Comment by birkenfeld** [comment]
Could the `:` in the ERROR comment be the problem?

**Comment by birkenfeld** [comment]
Hm, probably not, rather the location of the error is in `<std macros>` instead of the actual source file.

**Comment by mcarton** [comment]
That's why I though the problem might be in *compiletest_rs* (or I'm missing some syntax to indicate the error in that case). The colon in `ERROR:` should not be a problem, check `cyclomatic_complexity.rs`.

**Comment by Manishearth** [comment]
The error is because you used a span from a macro; not compiletest's fault:

```
<std macros>:3:1: 6:17 error: You probably are missing some parameter in your `panic!` call
<std macros>:3 $ crate:: rt:: begin_unwind (
<std macros>:4 $ msg , {
<std macros>:5 static _FILE_LINE : ( & 'static str , u32 ) = ( file ! (  ) , line ! (  ) ) ;
<std macros>:6 & _FILE_LINE } ) } ) ; ( $ fmt : expr , $ ( $ arg : tt ) + ) => (
tests/compile-fail/panic.rs:7:5: 7:18 note: in this expansion of panic! (defined in <std macros>)
tests/compile-fail/panic.rs:4:8: 4:20 note: lint level defined here
tests/compile-fail/panic.rs:4 #[deny(panic_params)]
                                     ^~~~
```

You should pick a span that covers the entire macro. This might be nontrivial to obtain, but it seems possible if you tweak the lint so that it looks for Exprs that correspond to the *entire*  `panic!()` expansion

**Comment by Manishearth** [comment]
Fixed it, used expninfo

**Comment by Manishearth** [comment]
https://github.com/Manishearth/rust-clippy/commit/dbf1cdf34aa89cdaba1bb9993e6aed221dfceb90

**Comment by mcarton** [comment]
Thanks :smile:

**Pull request merged**
