### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by afck**

### CODE REVIEW

**Comment by llogiq** [comment]
Thank you for submitting this PR! You may want to update the respective tests, too. And perhaps run `util/update_lints.py` to be sure.

**Comment by afck** [comment]
These are just two typos. The test failure doesn't seem to be related to this.

**Comment by mcarton** [comment]
@afck There’s new (relevant) errors now. When you update a message, you have to update the tests accordingly :smile:

**Comment by afck** [comment]
Ah, sorry, I hadn't realized that the messages are in the tests verbatim, because of the other errors!
Fixed now.

**Comment by mcarton** [comment]
Thanks!

**Pull request merged**
