### PR TITLE
Lints about `new` methods

### LINKED ISSUE #618: lint: wrong constructor
Should lint `new(..)` methods that take a `Self` argument (which should be either `.clone()` or `.with_..(..)`) or don't return a `Self`. `warn` by default.

### PR DESCRIPTION
**Pull request by mcarton**
Fix #618.

Edit: hum, should we allow:
```rust
impl Foo {
    fn new(..) -> Result<Foo, Error> { .. }
}
```
too?

### CODE REVIEW

**Comment by llogiq** [comment]
Yeah, we probably should allow `Result<Self, _>`.

**Comment by mcarton** [comment]
Yup, there are some examples in `rustc` (eg. `term::terminfo::TerminfoTerminal::new(out: T) -> Option<TerminfoTerminal<T>>`). I’ll do that tomorrow.

**Comment by llogiq** [comment]
Nice.

**Comment by llogiq** [comment]
Good stuff. :+1:

**Pull request merged**
