### PR TITLE
Identity op now uses const folding, no longer follows const bindings

### LINKED ISSUE #183: identity_op lint triggers for constants
```rust
#![feature(plugin)]
#![plugin(clippy)]

const PANEL_Y: i32 = 0;

fn main() {
    println!("Drawing at {}", PANEL_Y + 14);
}

```

```
src/main.rs:7:31: 7:43 warning: the operation is ineffective. Consider reducing it to `14`, #[warn(identity_op)] on by default
src/main.rs:7     println!("Drawing at {}", PANEL_Y + 14);
                                            ^~~~~~~~~~~~
```

Here we want to draw at PANEL_Y + 14, not simply 14, even if the PANEL_Y constant happens to be 0 at this time, but it could change in the future.

### PR DESCRIPTION
**Pull request by llogiq**
This closes #183.

### CODE REVIEW

**Comment by Manishearth** [comment]
You seem to have based this off of the wrong branch?

**Comment by Manishearth** [comment]
oh, this never merged

**Comment by Manishearth** [comment]
LGTM

**Comment by llogiq** [comment]
This rebasing stuff still goes over my head when it's a) late or b) early and I haven't had enough coffee. Halp?

**Comment by Manishearth** [comment]
You don't need rebasing here :smile:

**Comment by llogiq** [comment]
Ok, r+?

**Pull request merged**
