### PR TITLE
Use rustc --print sysroot, bump to v66 r? @llogiq

### PR DESCRIPTION
**Pull request by Manishearth**

### CODE REVIEW

**Comment by oli-obk** [comment]
uhm... if rustc has that info, we should be able to extract the info programmatically. I'll investigate.

**Comment by oli-obk** [comment]
[Session::sysroot](http://manishearth.github.io/rust-internals-docs/rustc/session/struct.Session.html#method.sysroot)... let's use that xD

**Comment by cuviper** [comment]
I would suggest ditching RUSTUP/MULTIRUST environment entirely in favor of this.

**Comment by Manishearth** [comment]
I prefer relying on env vars over shelling out since the setup could be complicated.

**Pull request merged**
