### PR TITLE
Tweak HTML version of docs with scroll to lints

### LINKED ISSUE #1181: Interlinks and filters on gh-pages
Copied from https://github.com/Manishearth/rust-clippy/pull/1091#issuecomment-240889966.

---

* Go on https://manishearth.github.io/rust-clippy/v0.0.84/
* Set filter “break”
* Open “wrong_pub_self_convention”
* Click on the first link: “This is the same as [`wrong_self_convention`](https://manishearth.github.io/rust-clippy/current/#wrong_self_convention), but for public items.”
⇒ *Nothing happens.*

Expected result: the filter vanishes and the page jumps to the lint.

Cc @killercup.

### PR DESCRIPTION
**Pull request by killercup**
Clicking on internal links in lint docs now jumps to the linked lint. The same magic is also used to scroll down and open lint docs when visiting the page with an anchor link.

Uses good old DOM events and wibbly-wobbly timeouts to wait for angular to render this huge list of lints.

Fixes #1181

r? @mcarton

### CODE REVIEW

**Comment by mcarton** [comment]
That does not seem to work.
When I open directly `{firefox,chromium} http://0.0.0.0:8000/#useless_let_if_seq` it does jump to the lint and open it.

But if I click on a link:
* in firefox with a `file:` protocol scheme, the filter is removed, and that's it;
* in firefox with a `http:` protocol scheme¹, nothing happens;
* (chromium refuses to load Angular with a `file:` protocol scheme;)
* in chromium with a `http:` protocol scheme¹, the filter is removed and it jumps to the lint article, but does not expand it.

---

1: with `python -m http.server`

**Comment by killercup** [comment]
file protocol should *not* work. I'll look into the other issues. Only
tested with safari so far.

Martin Carton <notifications@github.com> schrieb am So. 28. Aug. 2016 um
18:39:

**Comment by mcarton** [comment]
> file protocol should *not* work

Maybe, but I spontaneously tried `firefox utils/gh-pages/index.html`. I would not have even though to try with a local HTTP server if not for the chromium error :sweat_smile:

**Comment by killercup** [comment]
Updated with a slightly crazy fix. Okay, okay, it's more of a totally-crazy-but-probably-best-practice-anyway kind of fix.

Btw, the easiest solution to making this work using `file:///` would be to embed all resources in the same file.

**Comment by mcarton** [comment]
> Btw, the easiest solution to making this work using `file:///` would be to embed all resources in the same file.

Oh I don't actually care about that. It's just that I tried that first and seeing it did not work had to google “python http server” :sweat_smile:

**Comment by mcarton** [comment]
Thanks! Seems to work now.

**Pull request merged**
