### PR TITLE
Make most tests an `example` so we can run them one by one

### PR DESCRIPTION
**Pull request by oli-obk**
This allows us to go into the `clippy_tests` directory and run `cargo build --example foo` to produce just the output of example `foo`.

Also we don't duplicate build times anymore between `clippy_lints` and `clippy` due to workspaces.

Next step: Run rustfix on our examples and compare the output to `example_name.rustfix` to see what the suggestions we produce actually mean

### CODE REVIEW

**Comment by oli-obk** [comment]
Oh and we don't need to run `update_...sh` anymore for the examples. They update automatically when running cargo test on the main repository.

The number of travis cache invalidations should go down significantly now, too.

**Comment by oli-obk** [comment]
Opinions anyone?

**Comment by Manishearth** [comment]
I like this idea! r=me

Didn't look too closely at test changes, but aside from that looks good.

**Comment by mcarton** [comment]
Same here, just a few remarks:

* `CONTRIBUTING.md` needs to be updated;
* how do you choose what is an example and what is still a UI test?
* did you really mean to commit ` rust-clippy/clippy_tests/src/lib.rs` ?
* why do we need a new crate?

**Comment by oli-obk** [comment]
> how do you choose what is an example and what is still a UI test?

Examples are things that compile successfully. I also left some things as ui tests that needed compiletest support for ignoring tests with conditions

> did you really mean to commit rust-clippy/clippy_tests/src/lib.rs ?

yea, it could be empty or sth. It's just there so the crate compiles

> why do we need a new crate?

because you'll go crazy if you run cargo test on the main project and it compiles all examples and spits out a wall of text. We'd need to disable examples building for tests for each example one by one in the Clippy.toml, which doesn't scale nicely.

> CONTRIBUTING.md needs to be updated;

will do

**Comment by crumblingstatue** [comment]
Is it an intended consequence of this that `cargo-clippy` is now built into `clippy-tests/target` instead of `target` at the root?

**Comment by oli-obk** [comment]
Yes. Everything is compiled in clippy-tests/target. We could swap it around, but it would take some effort and I'm not sure how useful it would be.

**Comment by crumblingstatue** [comment]
It's a bit counter-intuitive, because usually the user looks for the binaries inside `target` at the root. And it doesn't make much sense to find an end-user binary in a folder called tests. This broke my symlink to cargo-clippy, and I had to search for it before I found it.

**Comment by oli-obk** [comment]
Workspaces are somewhat counter-intuitive ;) Maybe I'm doing this wrong.

Anyway, the location and names of the generated binaries are completely unstable. It would probably be advisable to use `cargo install` with a custom path to install it to the location from which it should run. But without knowing more about your setup I'm not sure.

**Comment by crumblingstatue** [comment]
Technically, the workspace could be at the crate root, unless that's not feasible somehow. I usually define my workspaces at the crate root.

But if clippy-tests is a desirable place for cargo-clippy, I can live with that.

**Comment by oli-obk** [comment]
I tried making the repository root also the workspace. But the issue is that we can't have clippy-tests depend on clippy without clippy-tests being the workspace root. The workspace root needs to be the only crate that no other crate depends on, but it must depend on all crates in the workspace (indirectly is fine).

> But if clippy-tests is a desirable place for cargo-clippy, I can live with that.

It is not, this is just a side effect of workspaces placing the binaries into the workspace root's target directory instead of every crate's target directory. To me the `target` directories are just caches and their contents could just as well be erased right after `cargo run` or `cargo test` finishes. All that would change is that everything would get really slow (which is the normal expectation when you disable caches).

**Comment by crumblingstatue** [comment]
Alright, thanks for the explanation!

**Pull request merged**
