### PR TITLE
Prefer `.cloned()` over `.map(|x| x.clone())`

### PR DESCRIPTION
**Pull request by wartman4404**
Implicit cloning by dereferencing Copy types is included as well.  It seems to be almost as common, at least in the code I've written.

I feel like I'm misusing `if_let_chain!()`, I hope not too badly...

### CODE REVIEW

**Comment by llogiq** [comment]
Looks good, just one potential problem: The `deref_only` part may lead to false positives if the Deref contains an implicit type conversion (e.g. `syntax::ptr::P<T>` derefs to `T`, whereas `.clone()` will create another `P<T>`.

**Comment by wartman4404** [comment]
You're right, I completely overlooked that.  I figured the `walk_ptrs_ty_depth` check would avoid it, but it didn't work if you derefed a `&P<T>` twice.

**Comment by llogiq** [comment]
Do you need help with the check? I think we should have something similar in `eta_reduction.rs`.

**Comment by wartman4404** [comment]
Sorry, it's been done for a little while, but I force-pushed the change, which wasn't very helpful of me.  I moved the check in `eta_reduction.rs` into `util.rs`, I hope that's okay.

**Comment by Manishearth** [comment]
Force push is fine with us

**Comment by llogiq** [comment]
Yes, I just overlooked it. I'll merge.

**Pull request merged**
