### PR TITLE
extend_from_slice lint

### LINKED ISSUE #572: suggest extend_from_slice instead of extend
Obviously only for `Vec`s. This is very similar to our `str_to_string` lint.

### PR DESCRIPTION
**Pull request by llogiq**
This closes #572

### CODE REVIEW

**Comment by fhartwig** [comment]
It would be good if this lint also caught `v.extend(&vec![1, 2, 3])` and `v.extend(&[1, 2, 3].iter())`.

**Comment by llogiq** [comment]
I think it should catch the first, but l need to add some code for the second.

**Comment by fhartwig** [comment]
If I add

    v.extend(&vec!["foo", "bar"]); //~ERROR use of `extend`

to your tests, the tests fail, so the first case doesn't seem to be covered. Which makes sense, I think, because the `derefs_to_slice` has no match arm that would catch `&Vec`.

**Comment by fhartwig** [comment]
(Just throwing this idea out there. Might be rubbish)

Maybe it would be easier to look at the argument to `extend` and look up the `IntoIterator` impl for its type. If `IntoIterator::IntoIter` is `std::slice::Iter`, then suggest using `extend_from_slice`. I think this would catch all the obvious candidates for this lint.

**Comment by Manishearth** [comment]
> Maybe it would be easier to look at the argument to extend and look up the IntoIterator impl for its type. 

That works, but we still have to handle deref coercions :smile:

**Comment by fhartwig** [comment]
> That works, but we still have to handle deref coercions :smile:

Would we? For `&Vec<T>` we wouldn't, because `IntoIterator` is implemented on `&Vec`, no coercions needed. But deref coercions confuse me, so I'm probably missing the cases where we need them.

**Comment by llogiq** [comment]
I took the easy route and checked directly for Vec.

**Comment by fhartwig** [comment]
This is turning out to be more complicated than I thought :smile: 
I think we need to also check that the type parameter for the vector is `Clone`, since `extend_from_slice` is only implemented for `Vec<T: Clone>`.

**Comment by llogiq** [comment]
So do I understand this correctly?

|Argument|should lint|
|-------------|-------------|
|&[T]        |yes          |
|&[T; N]    |yes          |
|&mut [T] |why not?  |
|&Vec       |yes         |
|&mut Vec|sure        |
|Vec         |no           |
|&str        |what are you smoking?|

**Comment by fhartwig** [comment]
@llogiq Yeah, that's what I think. I'd also add `std::slice::Iter` and `std::slice::IterMut`.

**Comment by llogiq** [comment]
I still need to change this to replace the .iter() call with an "&" in the suggestion.

**Comment by llogiq** [comment]
@Manishearth: r? (But first I'll merge from master and re-run update_lints.py)

**Comment by llogiq** [comment]
If we merge this, we have :100: lints.

**Comment by Manishearth** [comment]
Woooo :100:

**Pull request merged**
