### PR TITLE
simplify `mut_mut` lint

### PR DESCRIPTION
**Pull request by oli-obk**

### CODE REVIEW

**Comment by mcarton** [comment]
Looks like we need to rustup. I could do that later today.

**Comment by mcarton** [comment]
Does this fix #939?

**Comment by oli-obk** [comment]
no, it doesn't change anything, it's just a refactoring, because I couldn't grok it due to the various functions and map calls

**Comment by oli-obk** [comment]
rustup done. This removed some code explicitly written for `self` from the lifetime checks. HIR is great!

**Comment by mcarton** [comment]
@oli-obk sorry, I did not notice that you had rustuped in this PR and did it in #942, there is now merge conflicts.

**Comment by oli-obk** [comment]
rebased

**Comment by oli-obk** [comment]
rebased

**Pull request merged**
