### PR TITLE
rustup

### PR DESCRIPTION
**Pull request by birkenfeld**

### CODE REVIEW

**Comment by birkenfeld** [comment]
Test failure seems unrelated - is the bug in clippy or rustc?

**Comment by mcarton** [comment]
@birkenfeld it looks related.
See https://github.com/rust-lang/rust/pull/35605/files#diff-bab18e2cba63e19e514ac06a633a873cL1605, you might need something similar [there](https://github.com/Manishearth/rust-clippy/blob/master/clippy_lints/src/derive.rs#L109).

**Comment by birkenfeld** [comment]
Yep, the index changed. Thanks!

**Comment by mcarton** [comment]
Published.

**Pull request merged**
