### PR TITLE
Add forget_ref lint.

### LINKED ISSUE #1353: mem::forget(&_) forgets the ref, not the data
We should lint `mem::forget(&_)` as it doesn't forget the referenced value.

### PR DESCRIPTION
**Pull request by theemathas**
Fixes #1353.

### CODE REVIEW

**Comment by oli-obk** [comment]
Lgtm. Please rebase and rerun update_lints

**Comment by theemathas** [comment]
Done!

**Comment by theemathas** [comment]
Did I do something wrong to upset appveyor? D:

**Comment by Manishearth** [comment]
Appveyor is still being set up, ignore it.

**Pull request merged**
