### PR TITLE
process more kinds of metadata

### LINKED ISSUE #973: `cargo clippy` panics with 'could not obtain cargo metadata'
I am trying to run `cargo clippy` 0.0.71 on the Hoverbear/rust-rosetta repository.

I installed `cargo clippy` with `rustup run nightly cargo install clippy`.

The repository has a toolchain override pointing to the latest nightly.

```
$ rustc --version
rustc 1.11.0-nightly (601eb13dc 2016-05-31)
$ env RUST_BACKTRACE=1 cargo clippy
thread '<main>' panicked at 'could not obtain cargo metadata: Json(ExpectedError("Object", "\"pattern\""))', ../src/libcore/result.rs:785
stack backtrace:
   1:     0x7f2a8b34b3e4 - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:     0x7f2a8b3599ab - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:     0x7f2a8b3595e3 - std::panicking::default_hook::he0146e6a74621cb4
   4:     0x7f2a8b31c92d - std::panicking::rust_panic_with_hook::h587239a80cad02d2
   5:     0x7f2a8b359c41 - std::panicking::begin_panic::h77cefecf7d758cdf
   6:     0x7f2a8b31ea7a - std::panicking::begin_panic_fmt::hb3024643f3039337
   7:     0x7f2a8b359bd1 - rust_begin_unwind
   8:     0x7f2a8b3a309f - core::panicking::panic_fmt::h5594591d20dedfcd
   9:     0x55c0355a37ae - core::result::unwrap_failed::h5961dc49f071615e
  10:     0x55c0355a224c - cargo_clippy::main::hd4e6cdc692d85a27
  11:     0x7f2a8b359088 - std::panicking::try::call::hd0906b54b9bfbb20
  12:     0x7f2a8b36832b - __rust_try
  13:     0x7f2a8b3682ce - __rust_maybe_catch_panic
  14:     0x7f2a8b358abc - std::rt::lang_start::hfe4efe1fc39e4a30
  15:     0x7f2a8a7a6740 - __libc_start_main
  16:     0x55c035598838 - _start
  17:                0x0 - <unknown>
error: 

```

Please let me know if I can provide more information. This crate is an interesting case because it has a large number of binaries that do not share a main library.

### PR DESCRIPTION
**Pull request by oli-obk**
partially fixes #973

That metadata format is a mess and I couldn't find a formal description of it...

### CODE REVIEW

**Comment by mcarton** [comment]
Couldn’t we use the `cargo` crate to get those information?

**Comment by oli-obk** [comment]
nope, it's mostly private :( That was actually the first thing I tried.

**Comment by oli-obk** [comment]
fixed the indexing failure

**Comment by llogiq** [comment]
Is #973 now completely fixed or should we reopen?

**Comment by mcarton** [comment]
Arf, “partially fixes #973” closes the issue and GitHub does not send mails for events that originate because something one does :cry:.

**Pull request merged**
