### PR TITLE
Upgrade regex to 0.2

### PR DESCRIPTION
**Pull request by upsuper**

### CODE REVIEW

**Comment by llogiq** [comment]
Looks good to me – will merge once travis succeeds (appveyor is known to fail for now).

**Comment by upsuper** [comment]
Locally I saw the same failure as well, but after I removed the `target` directory and built again, everything worked fine. So it probably needs a clean rebuild.

**Comment by oli-obk** [comment]
I cleared the caches and restarted travis.

**Comment by llogiq** [comment]
Thanks, @oli-obk

**Comment by oli-obk** [comment]
published 0.0.107

**Pull request merged**
