### PR TITLE
don't say "did you mean to" - use the standard "consider..."

### PR DESCRIPTION
**Pull request by birkenfeld**
"Did you mean to ..." sounds a bit condescending to me, since
if I meant to write "if let" I probably wouldn't have written "match" :)

### CODE REVIEW

**Comment by birkenfeld** [comment]
Also, this avoids ugly `?,` punctuation clash in rustc messages.

**Comment by Manishearth** [comment]
Oh, this is an artefact from the times when all clippy lint messages were structured as "You seem to be trying to X, did you mean to Y?", mimicking the original Microsoft Office Clippy.

Feel free to deviate from that style, at the time clippy was more of a joke repo (though it _was_ supposed to be helpful), but now that non-newbies are using it too, we should change the language.

**Comment by Manishearth** [comment]
r+

**Comment by llogiq** [comment]
Maybe we should make it even more impersonal by changing "you seem to *xy*" to "*xy* detected"?

**Comment by birkenfeld** [comment]
> mimicking the original Microsoft Office Clippy.

Yeah, I forgot :)

**Pull request merged**
