### PR TITLE
new lint: using collect() to just exhaust an iterator

### PR DESCRIPTION
**Pull request by birkenfeld**
Should use a for loop instead.

Could also use `foreach` from itertools, but I don't know if we want to advertise third-party crates. Maybe only in the Wiki.

(based on while-let loop lint branch, so that I don't need to rebase)

### CODE REVIEW

**Comment by birkenfeld** [comment]
@llogiq r?

**Comment by llogiq** [comment]
LGTM.

**Comment by Manishearth** [comment]
Personally feel that the collect lint should be allow, but it's not a strong preference so this is okay too.

**Comment by birkenfeld** [comment]
Hm, I guess for me that depends on the performance aspect: Is constructing the vector optimized away in these cases? If not, does a `Vec<()>` allocate?

[I suppose that one could also add a `FromIterator` instance for `()`, which just consumes the iterator and returns `()`. Then behavior can be explicitly selected by `collect::<()>()` (which still looks a bit ugly).]

**Comment by Manishearth** [comment]
I believe it does not, but I'm not sure. I do know that `Vec<()>` has some special handling

**Pull request merged**
