### PR TITLE
Casts : architecture independent handling of *size types

### PR DESCRIPTION
**Pull request by Robzz**
This is not finished yet, but I opened the PR to discuss a dilemma I'm having about something that slipped unnoticed and IMO deserves some more discussion, at `types.rs:220-225` : 
```rust
if to_nbits < from_nbits ||
    (!cast_from.is_signed() && cast_to.is_signed() && to_nbits <= from_nbits) {
        span_lint(cx, CAST_POSSIBLE_TRUNCATION, expr.span,
                  &format!("casting {} to {} may cause truncation of the value", cast_from, cast_to));
}
```
To put back in context, it handles the casts between integral types. My concern is about the second part of the condition. I initially wrote it with the rationale that u32::MAX > i32::MAX, therefore overflow is possible, but we changed the lint to be about truncation, since this is what rustc actually performs. Furthermore, the rustonomicon states :

> casting between two integers of the same size (e.g. i32 -> u32) is a no-op

Which clearly means that no truncation can occur in that case. This would have been correct when we were talking about "possible overflow", but since rustc actually performs truncation, I think we should get rid of the `|| (!cast_from.is_signed() && cast_to.is_signed() && to_nbits <= from_nbits)` part.

@llogiq What is your opinion about this?

### CODE REVIEW

**Comment by llogiq** [comment]
Good catch – in that case there *is* a kind of overflow (because large values become negative), but no truncation. I think we should add a fourth `cast_possible_wrap` lint category for this.

**Comment by Robzz** [comment]
I'm on it. However, this + handling `*size` separately creates a *lot* of corner cases. I updated the test case to get an idea of how many there are. I think I caught all of them, but I could have forgotten some, so fresh eyes are appreciated.

I also shortened/uniformized the wording of the messages because I was getting a bit lost and some lines were getting fairly long, but I don't think I've altered their meaning (not to the point of being wrong that is) or helpfulness. I also tried to make the test case more readable, as it's getting a bit complex.

Now that I have a presumably complete list of the corner cases to catch, I'll resume working on the implementation.

**Comment by Robzz** [comment]
I now have some refactoring to do, but I think this works.

**Comment by Robzz** [comment]
The code is now back to being readable, I'm actually quite pleased with how it looks. As far as I can tell, this should be good.

Being a complete github noob, I have to ask : I had to merge changes from this repo into my branch for github to consider this PR as mergeable. If you merge this PR, will github be smart enough to merge only my changes or do I need to rebase over an up-to-date branch? I'm thinking the former, but better safe than sorry.

**Comment by Manishearth** [comment]
No, github will include a mangled history. When you want to pull in updated changes, it's always better to rebase or `git pull --rebase`. I can rebase while merging if you're not comfortable with it though.

**Comment by Robzz** [comment]
Well I'm gonna have to learn how to do it eventually, so I might as well do it now. Seems like I have some reading to do :)

**Comment by llogiq** [comment]
Yeah, I only learned about that recently, too. I'm only slowly getting comfortable with `meld` (Btw. when git shows you some conflicts, `git mergetool` is your friend).

**Comment by llogiq** [comment]
Btw. I've now started to amend my commits with `git commit --amend`. This will need `--force` to `push`, but the resulting history looks much better.

**Comment by Robzz** [comment]
Yeah meld is my mergetool of choice too :) I usually use amending to edit my commit message after the fact, but I prefer rebase when I need to edit the contents of the commit, though this is purely a personal preference. I actually did the refactoring in 3 or 4 commits, and squashed them together by rebasing. However I didn't know about `git pull --rebase`, this is gonna be very useful!
Since we're sharing git tips, I recently discovered [git hooks](http://www.git-scm.com/book/en/v2/Customizing-Git-Git-Hooks), that's pretty cool stuff, I no longer have to worry about tabs, trailing whitespace, or forgetting to run the test suite :smile:

About rebasing this PR, I didn't get much time today and since I can now barely keep my eyes open, I'd rather do it tomorrow than do a half assed job today, but at least I think I figured out how to do it correctly. Btw, did any of you have any remarks or suggestion about the PR?

**Comment by Manishearth** [comment]
FWIW I find this meld setup to be quite useful:

```
[merge]
tool = mymeld
conflictstyle = diff3
[mergetool "mymeld"]
cmd = meld $LOCAL $BASE $REMOTE --output $MERGED
```
I'll have a look at the PR tomorrow, got stuff to study for today

**Comment by birkenfeld** [comment]
I seem to be the only one who prefers good old conflict markers (albeit aided by smerge-mode) ;)

**Comment by Robzz** [comment]
Since @llogiq added sections on the wiki for the previous 3 cast related lints, I [added one](https://github.com/Manishearth/rust-clippy/wiki#cast_possible_wrap) for the new lint that comes with this PR. Feel free to correct any inaccuracies :)

**Comment by llogiq** [comment]
I would have done it eventually, but you beat me to it. Thanks!

**Pull request merged**
