### PR TITLE
fix for latest nightly

### PR DESCRIPTION
**Pull request by hobofan**
Fixes breakage introduced by rust-lang/rust#30043

### CODE REVIEW

**Comment by hobofan** [comment]
Blocked by https://github.com/rust-lang-nursery/regex/pull/135

**Comment by llogiq** [comment]
Thanks! :+1: We'll merge when nightly catches up :smile:

**Comment by llogiq** [comment]
Seems to have hit. r+

**Comment by mrmonday** [comment]
When this is merged, could you make sure to bump the crate version number too?

I keep having to poke @Manishearth to update it on IRC each time clippy breaks on nightly.

**Comment by llogiq** [comment]
OK, I'll try – whether I succeed depends on me being awake when it lands. :smile:

**Comment by Manishearth** [comment]
I'll remember, don't worry.

**Comment by Manishearth** [comment]
Merging this, since everything else passes and it's been a few days since I opened the regex PR (and folks are complaining about broken clippy).

Also, published a new clippy

**Comment by llogiq** [comment]
Ok, but tests will fail then. Perhaps we should find another way to test our external macro check that doesn't require regex?

**Comment by Manishearth** [comment]
Ok with disabling the macro test temporarily.

**Comment by Manishearth** [comment]
We could write some convoluted macro tests I guess.

**Comment by llogiq** [comment]
That will only work if we put it in its own crate (which was the point of using regex in the test in the first place).

**Comment by Manishearth** [comment]
We can provide auxiliary files for compiletest. not sure if that works out of tree.

Or use a path dep to a local crate

**Comment by llogiq** [comment]
Yeah, that would work.

**Pull request merged**
