### PR TITLE
Rustup to *rustc 1.14.0-nightly (f09420685 2016-10-20)* and bump to 0.0.96

### PR DESCRIPTION
**Pull request by mcarton**
0.0.95 compiles on the latest nightly, but is buggy with macros (see [Travis](https://travis-ci.org/Manishearth/rust-clippy/builds/168036054)).
See https://github.com/rust-lang/rust/pull/37213.

### CODE REVIEW

**Comment by mcarton** [comment]
0.0.95 was published 17 days ago, is that a record? :stuck_out_tongue_winking_eye:

**Comment by Manishearth** [comment]
post-merge r+ 😄

**Comment by mcarton** [comment]
As usual, because it was broken, I merged as soon as Travis was green to publish it. But if you have any post-merge remark, just tell :innocent:

**Comment by Manishearth** [comment]
yep! (this was just a comment to signal to the other reviewers that they don't need to look at it 😄 . Though we don't have that strict a review policy so it doesn't really matter 😛 )

**Pull request merged**
