### PR TITLE
all: DRY for lint descriptions, prevent forgetting to add lints to the README

### PR DESCRIPTION
**Pull request by birkenfeld**
* use the rustc style for lint descriptions
* add a script to parse all lint descriptions and put the generated table into README

### CODE REVIEW

**Comment by birkenfeld** [comment]
[Rendered version of new README](https://github.com/birkenfeld/rust-clippy/blob/lint_descs/README.md)

**Comment by Manishearth** [comment]
LGTM. Could we generate the clippy lint group thing too?

**Comment by birkenfeld** [comment]
Sure!

**Comment by llogiq** [comment]
Yay! :smile:

**Pull request merged**
