### PR TITLE
fix typo in eval_order_dependence.rs

### PR DESCRIPTION
**Pull request by luisbg**
Fixing a "the the" to "the".

### CODE REVIEW

**Comment by luisbg** [comment]
Is it OK creating just a PR like this for a simple typo fix? or should I create an issue first to point at it?

**Comment by luisbg** [comment]
The CI errors are because of the "error: failed to extract package" that is happening with today's rustc nightly. :disappointed:

**Comment by Manishearth** [comment]
fine to just make PRs. thanks!

**Comment by luisbg** [comment]
Thanks Manish! :smiley:

**Pull request merged**
