### PR TITLE
New lint for zip with array length instead of enumerate()

### LINKED ISSUE #11: x.iter().zip(range(0,x.len()))
I have seen this a couple of times, don't know how easy it is to detect (given the variations) but the person *wants* is x.iter().enumerate().

### PR DESCRIPTION
**Pull request by nweston**
Fixes #11.

I have one question about this: I'm matching an expression like `x.iter().zip(0..x.len())` and I need to check that `.iter()` and `.len()` are called on the same thing. Right now I compare the `snippet()` of the two expressions but that seems kludgey. Is there a better way to check that two expressions are equivalent?

### CODE REVIEW

**Comment by Manishearth** [comment]
"x" and "y" will be ExprPaths

**Comment by nweston** [comment]
In this example, sure. But in practice it could be something more complicated (a method call that returns a vector, for example). Unless we want the lint to ignore anything that isn't an `ExprPath`.

**Comment by Manishearth** [comment]
The method call could return a different vector each time. So yeah, simple variable access only :smile:

**Comment by llogiq** [comment]
Yeah, perhaps we could allow simple blocks, like `{x}`, but I wouldn't do anything more complex.

**Comment by nweston** [comment]
OK, I changed it to expect `ExprPath` in both places and compare those.

**Comment by llogiq** [comment]
Thanks for the PR!

**Pull request merged**
