### PR TITLE
don't require `cargo clippy` to pass a `--lib` or `--bin x` argument

### LINKED ISSUE #935: Bad error running `cargo clippy` on multiple crate project
When I run this on rustup.rs I see:

```
brian@ip-10-234-25-118:~/dev/rustup.rs⟫ cargo clippy
error: extra arguments to `rustc` can only be passed to one target, consider filtering
the package by passing e.g. `--lib` or `--bin NAME` to specify a single target
thread '<main>' panicked at 'cargo rustc failed', /home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/lib.rs:131
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error:
```

cargo 0.11.0-nightly (5cb2bb1 2016-05-14)

rustc 1.10.0-nightly (5ebe41835 2016-05-15)

clippy 0.0.67

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #935

### CODE REVIEW

**Comment by oli-obk** [comment]
now that we have a metadata parser, we can check the version of `clippy` vs `clippy-lints` by using that metadata parser ^^ no need for text-parsing

**Comment by Manishearth** [comment]
That works, just add something in `tests/` I geuss?

**Comment by oli-obk** [comment]
done

**Comment by llogiq** [comment]
Cool! I've wanted this for some time. :smile:

**Pull request merged**
