### PR TITLE
fix enum glob use (again)

### LINKED ISSUE #686: ICE in `enum_glob_use`
```rust
#![feature(plugin)]
#![plugin(clippy)]

mod tests {
    use super::*;
}
```

produces

```
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'couldn't find node id 0 in the AST map', ../src/librustc/front/map/mod.rs:383
stack backtrace:
   1:     0x7f427c003760 - sys::backtrace::tracing::imp::write::hef3f5235812bde76Qwu
   2:     0x7f427c00c6bb - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43471
   3:     0x7f427c00c213 - panicking::default_handler::hb72e26fd774dcea5E3y
   4:     0x7f427bfd509c - sys_common::unwind::begin_unwind_inner::hcccaf464c9787883Flt
   5:     0x7f427bfd5b38 - sys_common::unwind::begin_unwind_fmt::h522f8632783201c5Lkt
   6:     0x7f427929f6b8 - front::map::Map<'ast>::get_if_local::h2ef219601d51bc0eOCe
   7:     0x7f426f952390 - enum_glob_use::EnumGlobUse::lint_item::h281ed1ce473f6fb73Sd
                        at /home/martin/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.42/src/enum_glob_use.rs:47
   8:     0x7f426f896467 - enum_glob_use::EnumGlobUse.LateLintPass::check_mod::h524de66907771adcqSd
                        at /home/martin/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.42/src/enum_glob_use.rs:34
   9:     0x7f42794cf6aa - lint::context::LateContext<'a, 'tcx>.hir_visit..Visitor<'v>::visit_mod::h5eb8589b7340079fAav
  10:     0x7f42794cb1f7 - lint::context::LateContext<'a, 'tcx>.hir_visit..Visitor<'v>::visit_item::h5dba0597da03fddf9Yu
  11:     0x7f42794cf74b - lint::context::LateContext<'a, 'tcx>.hir_visit..Visitor<'v>::visit_mod::h5eb8589b7340079fAav
  12:     0x7f42794f0688 - lint::context::check_crate::h38b43621c57cfa18eWv
  13:     0x7f427c525d15 - driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::closure.28316
  14:     0x7f427c51f574 - middle::ty::context::ctxt<'tcx>::create_and_enter::h12643393989740813000
  15:     0x7f427c51b6d1 - driver::phase_3_run_analysis_passes::h16655559552673494589
  16:     0x7f427c4ec59a - driver::compile_input::hdb23a384796401a8Bca
  17:     0x7f427c4dbac2 - run_compiler::hed51cbd6d1d8009fHOc
  18:     0x7f427c4d8f91 - sys_common::unwind::try::try_fn::h9037273685980418776
  19:     0x7f427c00108b - __rust_try
  20:     0x7f427bff96bd - sys_common::unwind::inner_try::h97bd458fb1ab729eHit
  21:     0x7f427c4d97e0 - boxed::F.FnBox<A>::call_box::h8520664474928706484
  22:     0x7f427c00ac80 - sys::thread::Thread::new::thread_start::hbf912636ac462411Y0x
  23:     0x7f42747d44a3 - start_thread
  24:     0x7f427bc8913c - clone
  25:                0x0 - <unknown>
```

Spotted in the *range_map* crate.
cc @oli-obk.

### PR DESCRIPTION
**Pull request by oli-obk**
I basically implemented a non-panicking version of `get_if_local` :/

fixes #686

### CODE REVIEW

**Comment by oli-obk** [comment]
what happened to travis?

**Comment by Manishearth** [comment]
IIRC github notifications are being sluggish

**Comment by mcarton** [comment]
> I basically implemented a non-panicking version of `get_if_local` :/

That function is weird, it’s a convenience function that returns `Option<_>` but has a failure case :/

**Comment by Manishearth** [comment]
Yeah, I was chatting with @eddyb about it.

The fact that `super` doesn't have a working defid is more disconcerting.

**Comment by mcarton** [comment]
I don’t know about travis, but the PR fixes the problem in `range_map` locally here, thanks.

**Comment by Manishearth** [comment]
yo travis wake up

**Pull request merged**
