### PR TITLE
match .map(Clone::clone)

### LINKED ISSUE #436: False negative on `map_clone`
The lint fails to catch `x.iter().map(Clone::clone)` – while not too common, it's valid Rust code and does the same thing as a closure.

### PR DESCRIPTION
**Pull request by llogiq**
I think there may be a problem if someone implements their `own::clone::Clone`, but this is highly unlikely.

This closes #436.

### CODE REVIEW

**Comment by Manishearth** [comment]
r+

Should we be ensuring a cloned() method exists first?

**Comment by llogiq** [comment]
How did I miss that? Currently the code assumes that whatever implements `.map(_)` also implements `.cloned()`.

**Comment by Manishearth** [comment]
I know the assumption already exists; I'm suggesting we eventually get rid of it :smile:

**Comment by Manishearth** [comment]
The build is broken because Rustc nightlies sort of exist and sort of don't right now.

**Comment by llogiq** [comment]
I think we may be able to reuse some of the code in `len_without_is_empty`.

**Comment by llogiq** [comment]
Doing this without introducing false negatives is surprisingly tricky – something about the arrays is throwing the method lookup off.

**Comment by llogiq** [comment]
I'll create another PR with the method check once I get it to work. Perhaps I need to do an additional lookup?

**Pull request merged**
