### PR TITLE
Markdown typo fix

### PR DESCRIPTION
**Pull request by sourcefrog**

### CODE REVIEW

**Comment by mcarton** [comment]
Thanks! But that file is generated from [that one](https://github.com/Manishearth/rust-clippy/blob/master/clippy_lints/src/collapsible_if.rs#L34-L36), can you change it there too?

**Comment by sourcefrog** [comment]
I can.

**Comment by mcarton** [comment]
@oli-obk by the way, isn't this the kind of things `remark-lint` should catch?

**Comment by oli-obk** [comment]
I'll investigate

**Pull request closed without merging**
