### PR TITLE
clean tests/ui/assign_ops.rs

### PR DESCRIPTION
**Pull request by luisbg**
When all //~ were removed from tests, these were replaced with empty
lines to leave the numbers in the expected stderr untouched.

Cleaning the empty lines for clarity.

If there is interest, I could slowly do the rest of the test files that have weird looking empty files. Happy to do so :smile:, the clone() lint I have assigned is taking me a bit more time of research.

### CODE REVIEW

**Comment by oli-obk** [comment]
Thanks! This is a good idea. You can probably just throw rustfmt on the tests (except those which care about formatting xD)

**Comment by luisbg** [comment]
@oli-obk cool! Will add an issue and assign it to myself.

No idea why the Travis checks failed

**Comment by oli-obk** [comment]
> No idea why the Travis checks failed

because compiletest_rs updated to the "latest nightly", which doesn't exist -.-

https://github.com/laumann/compiletest-rs/pull/63

**Comment by luisbg** [comment]
woot! All checks passed.

@oli-obk, thanks for re-triggering the tests.

**Comment by oli-obk** [comment]
Great! took a few tries xD

**Pull request merged**
