### PR TITLE
[rfc] consts: convert to using a struct with state

### PR DESCRIPTION
**Pull request by birkenfeld**
Struct has the context reference (as an Option) and the needed_resolution flag.

As suggested on reddit...

### CODE REVIEW

**Comment by llogiq** [comment]
We lost a way to determine whether resolution was needed if it's allowed, as far as I can see. Either have the complex version return a tuple or make the context-holding struct public.

**Comment by birkenfeld** [comment]
True, should be better now.

**Comment by llogiq** [comment]
LGTM.

**Pull request merged**
